# Generated by Django 3.0.5 on 2020-04-28 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0006_auto_20200427_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_hora_cierre', models.DateTimeField()),
                ('estado', models.CharField(default='Abierta', max_length=10)),
                ('aspirantes', models.ManyToManyField(to='usuarios.AspirantePerfil')),
                ('aspirantes_anonimos', models.ManyToManyField(to='usuarios.AnonimoPerfil')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.EmpresaPerfil')),
            ],
            options={
                'verbose_name': 'Convocatoria',
                'verbose_name_plural': 'Convocatorias',
                'ordering': ['fecha_hora_cierre'],
            },
        ),
    ]
