# Generated by Django 3.0.5 on 2020-04-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0002_auto_20200428_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'ABIERTA'), ('CERRADA', 'TERMINADA'), ('TERMINADA', 'TERMINADA')], default='ABIERTA', max_length=10),
        ),
    ]
