# Generated by Django 3.0.5 on 2020-04-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_auto_20200428_2144'),
        ('convocatoria', '0006_auto_20200428_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='aspirantes',
            field=models.ManyToManyField(to='usuarios.AspirantePerfil'),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='aspirantes_anonimos',
            field=models.ManyToManyField(to='usuarios.AnonimoPerfil'),
        ),
    ]
