# Generated by Django 3.0.5 on 2020-04-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20200427_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonimoPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('curriculo', models.FileField(upload_to='curriculos_anonimos')),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='es_anonimo',
        ),
    ]
