# Generated by Django 3.0.5 on 2020-04-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20200427_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='es_aspirante',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='es_empresa',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('Aspirante', 'Aspirante'), ('Empresa', 'Empresa')], default='Aspirante', max_length=10),
        ),
        migrations.AlterField(
            model_name='aspiranteperfil',
            name='curriculo',
            field=models.FileField(blank=True, upload_to='curriculos'),
        ),
    ]
