# Generated by Django 3.0.5 on 2020-04-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20200428_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('Aspirante', 'Aspirante'), ('Empresa', 'Empresa')], max_length=10),
        ),
    ]
