# Generated by Django 3.0.5 on 2020-04-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_auto_20200428_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('Aspirante', 'Aspirante'), ('Empresa', 'Empresa')], default='Aspirante', max_length=10),
        ),
    ]
