# Generated by Django 3.0.5 on 2020-04-29 05:19

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_auto_20200428_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonimoperfil',
            name='curriculo',
            field=models.FileField(upload_to='curriculos_anonimos', validators=[usuarios.models.validate_file_extension]),
        ),
    ]
