# Generated by Django 3.0.5 on 2020-04-29 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_auto_20200429_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
    ]
