# Generated by Django 3.0.5 on 2020-04-30 19:01

from django.db import migrations, models
import usuarios.validators


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_auto_20200429_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonimoperfil',
            name='curriculo',
            field=models.FileField(upload_to='curriculos_anonimos', validators=[usuarios.validators.validate_file_extension, usuarios.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='aspiranteperfil',
            name='curriculo',
            field=models.FileField(blank=True, upload_to='curriculos', validators=[usuarios.validators.validate_file_extension, usuarios.validators.validate_file_size]),
        ),
    ]
