# Generated by Django 3.0.5 on 2020-04-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_auto_20200430_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonimoperfil',
            name='id_convocatoria',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
